import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from 'react';
import { Dialog, DialogContent } from '@/app/components/ui/dialog';
import { cn } from '@/app/utils/cn';
import { Command as CommandPrimitive } from 'cmdk';
const Command = React.forwardRef(({ className, ...props }, ref) => (_jsx(CommandPrimitive, { ref: ref, className: cn('flex h-full w-full flex-col overflow-hidden rounded-2xl bg-background/95 text-foreground shadow-2xl', className), ...props })));
Command.displayName = CommandPrimitive.displayName;
const CommandDialog = ({ children, ...props }) => (_jsx(Dialog, { ...props, children: _jsx(DialogContent, { className: "overflow-hidden border-none bg-transparent p-0 shadow-none", children: children }) }));
const CommandInput = React.forwardRef(({ className, icon, ...props }, ref) => (_jsxs("div", { className: "flex items-center gap-2 border-b border-border px-4", children: [icon, _jsx(CommandPrimitive.Input, { ref: ref, className: cn('flex h-12 w-full bg-transparent text-sm text-foreground placeholder:text-muted-foreground focus:outline-none disabled:cursor-not-allowed disabled:opacity-50', className), ...props })] })));
CommandInput.displayName = CommandPrimitive.Input.displayName;
const CommandList = React.forwardRef(({ className, ...props }, ref) => (_jsx(CommandPrimitive.List, { ref: ref, className: cn('max-h-80 overflow-y-auto overflow-x-hidden px-2 py-3', className), ...props })));
CommandList.displayName = CommandPrimitive.List.displayName;
const CommandEmpty = CommandPrimitive.Empty;
const CommandGroup = React.forwardRef(({ className, ...props }, ref) => (_jsx(CommandPrimitive.Group, { ref: ref, className: cn('mb-4 space-y-1 px-2 text-xs text-muted-foreground', className), ...props })));
CommandGroup.displayName = CommandPrimitive.Group.displayName;
const CommandItem = React.forwardRef(({ className, ...props }, ref) => (_jsx(CommandPrimitive.Item, { ref: ref, className: cn('flex cursor-pointer select-none items-center gap-2 rounded-xl px-3 py-2 text-sm text-foreground outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50 data-[selected=true]:bg-foreground/10', className), ...props })));
CommandItem.displayName = CommandPrimitive.Item.displayName;
const CommandSeparator = React.forwardRef(({ className, ...props }, ref) => (_jsx(CommandPrimitive.Separator, { ref: ref, className: cn('-mx-2 my-2 h-px bg-border', className), ...props })));
CommandSeparator.displayName = CommandPrimitive.Separator.displayName;
const CommandShortcut = ({ className, ...props }) => (_jsx("span", { className: cn('ml-auto text-xs tracking-widest text-muted-foreground', className), ...props }));
CommandShortcut.displayName = 'CommandShortcut';
export { Command, CommandDialog, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem, CommandSeparator, CommandShortcut, };
