services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-phelia}
      POSTGRES_PASSWORD: ${DB_PASS:-phelia}
      POSTGRES_DB: ${DB_NAME:-phelia}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-phelia} -d ${DB_NAME:-phelia}"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      WEBUI_PORT: 8080
      TZ: ${TZ:-Etc/UTC}
    volumes:
      - qb_config:/config
      - downloads:/downloads
      - music:/music
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 30

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    env_file:
      - ./env/api.env
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER:-phelia}:${DB_PASS:-phelia}@db:5432/${DB_NAME:-phelia}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      QB_URL: http://qbittorrent:8080
      TZ: ${TZ:-Etc/UTC}
    command: ["/app/entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    volumes:
      - ../apps/api:/app
      - downloads:/downloads
      - music:/music
    ports:
      - "${API_PORT:-8000}:8000"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/api/v1/healthz').getcode()==200 else sys.exit(1)"
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s



  worker:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    env_file:
      - ./env/api.env
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER:-phelia}:${DB_PASS:-phelia}@db:5432/${DB_NAME:-phelia}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      QB_URL: http://qbittorrent:8080
      TZ: ${TZ:-Etc/UTC}
    command: ["celery","-A","app.services.jobs.tasks.celery_app","worker","-l","info","-O","fair"]
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      api:
        condition: service_started
    volumes:
      - ../apps/api:/app
      - downloads:/downloads
      - music:/music

  beat:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    env_file:
      - ./env/api.env
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER:-phelia}:${DB_PASS:-phelia}@db:5432/${DB_NAME:-phelia}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      TZ: ${TZ:-Etc/UTC}
    command: ["celery","-A","app.services.jobs.tasks.celery_app","beat","-l","info"]
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      api:
        condition: service_started
    volumes:
      - ../apps/api:/app

  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE}
        VITE_WS_BASE: ${VITE_WS_BASE}
    env_file:
      - ./env/web.env
    environment:
      VITE_API_BASE: ${VITE_API_BASE:-http://localhost:${API_PORT:-8000}/api/v1}
      VITE_WS_BASE: ${VITE_WS_BASE:-ws://localhost:${API_PORT:-8000}}
    ports:
      - "${WEB_PORT:-5173}:80"
    depends_on:
      api:
        condition: service_healthy


volumes:
  db_data:
  redis_data:
  qb_config:
  downloads:
  music:

